# Generated by Django 3.0.3 on 2020-02-07 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('price', models.IntegerField(help_text='cent')),
                ('quantity_available', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_email_address', models.EmailField(max_length=254)),
                ('date_order_placed', models.DateTimeField(auto_now_add=True)),
                ('date_order_updated', models.DateTimeField(auto_now=True)),
                ('order_status', models.CharField(choices=[('created', 'Created'), ('in_processing', 'In Processing'), ('canceled', 'Canceled'), ('delivered', 'Delivered')], max_length=50)),
                ('products', models.ManyToManyField(to='inventory.Product')),
            ],
        ),
    ]
